language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs-1"
  - "iojs-2"
  - "4"
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-djangular-gift' ]; then cd .. && eval "mv $currentfolder generator-djangular-gift" && cd generator-djangular-gift; fi
